#!/usr/bin/env node
/**
 * Batch content generation script
 * Usage: ANTHROPIC_API_KEY=sk-ant-... node scripts/generate-content.mjs
 *
 * Generates 36 learning units (6 scenes × 3 levels × 2 units each)
 * and writes them to apps/web/src/lib/content.ts
 */

import Anthropic from '@anthropic-ai/sdk'
import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
  baseURL: process.env.ANTHROPIC_BASE_URL,
})

const SCENES = [
  { id: 'daily',     label: '日常生活', prompts: ['在超市购物结账', '和邻居打招呼聊天'] },
  { id: 'work',      label: '职场英语', prompts: ['在会议上汇报项目进度', '和同事讨论解决方案'] },
  { id: 'travel',    label: '旅行出行', prompts: ['在机场办理值机手续', '在酒店前台办理入住'] },
  { id: 'social',    label: '社交闲聊', prompts: ['在派对上认识新朋友', '和朋友聊周末计划'] },
  { id: 'restaurant',label: '餐厅用餐', prompts: ['在餐厅点餐并询问推荐', '结账并给小费'] },
  { id: 'emergency', label: '紧急情况', prompts: ['在医院描述症状', '向路人寻求帮助'] },
]

const LEVELS = ['beginner', 'intermediate', 'advanced']

const LEVEL_DESC = {
  beginner:     'simple vocabulary, short sentences (A2-B1), very common phrases',
  intermediate: 'natural conversational English (B1-B2), some idioms',
  advanced:     'fluent idiomatic English (B2-C1), nuanced expressions',
}

async function generateUnit(scene, prompt, level, index) {
  const levelDesc = LEVEL_DESC[level]
  const msg = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 800,
    thinking: { type: 'disabled' },
    messages: [{
      role: 'user',
      content: `Generate a spoken English learning unit for Chinese learners.
Scene: "${prompt}"
Level: ${levelDesc}

Return ONLY valid JSON (no markdown, no explanation):
{
  "title": "short English phrase that captures the scene (max 6 words)",
  "dialogueText": "a natural 4-6 line spoken dialogue between two people (A: ... B: ... format)",
  "chunks": [
    { "id": "c1", "text": "key phrase 1 (2-6 words)", "scene": "one-line Chinese usage tip" },
    { "id": "c2", "text": "key phrase 2", "scene": "usage tip" },
    { "id": "c3", "text": "key phrase 3", "scene": "usage tip" },
    { "id": "c4", "text": "key phrase 4", "scene": "usage tip" }
  ]
}

Rules:
- dialogueText: natural spoken English only, no stage directions
- chunks: 4 high-frequency phrases, immediately usable in real life
- scene in chunks: practical tip like "结账时说" or "表示感谢时用"`
    }],
  })

  const text = msg.content.find(b => b.type === 'text')?.text ?? ''
  const parsed = JSON.parse(text)
  const unitId = `${scene.id}-${level}-${index + 1}`

  return {
    id: unitId,
    level,
    scene: scene.label,
    title: parsed.title,
    audioUrl: '',
    dialogueText: parsed.dialogueText,
    chunks: parsed.chunks.map((c, i) => ({
      id: `${unitId}-c${i + 1}`,
      text: c.text,
      audioUrl: '',
      scene: c.scene,
    })),
  }
}

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('Error: ANTHROPIC_API_KEY not set')
    process.exit(1)
  }

  const units = []
  let total = 0
  const totalCount = SCENES.length * LEVELS.length * 2

  for (const scene of SCENES) {
    for (const level of LEVELS) {
      for (let i = 0; i < scene.prompts.length; i++) {
        const prompt = scene.prompts[i]
        process.stdout.write(`[${++total}/${totalCount}] ${scene.label} · ${level} · ${prompt} ... `)
        try {
          const unit = await generateUnit(scene, prompt, level, i)
          units.push(unit)
          console.log('✓')
        } catch (e) {
          console.log(`✗ ${e.message}`)
        }
        // Rate limit: 1 req/s
        await new Promise(r => setTimeout(r, 1000))
      }
    }
  }

  // Write to content.ts
  const outPath = join(__dirname, '../src/lib/content.ts')
  const code = `// Auto-generated by scripts/generate-content.mjs — do not edit manually
// Run: ANTHROPIC_API_KEY=sk-ant-... node scripts/generate-content.mjs
import type { LearningUnit } from '@ds/types'

export const DAILY_UNITS: LearningUnit[] = ${JSON.stringify(units, null, 2)}
`
  writeFileSync(outPath, code, 'utf8')
  console.log(`\nWrote ${units.length} units to ${outPath}`)
}

main().catch(console.error)
